version: '3.9'

services:
  # ------------------- KAFKA (Redpanda) -------------------
  kafka:
    image: redpandadata/redpanda:v23.3.18
    container_name: kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      - --advertise-kafka-addr INTERNAL://kafka:9092,EXTERNAL://localhost:19092
    ports:
      - "19092:19092"

  # ------------------- MONGODB -------------------
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27018:27017"

  # ------------------- TRACKING SERVICE -------------------
  tracking-service:
    build:
      context: ./tracking-service
    container_name: tracking-service
    depends_on:
      - kafka
      - mongodb
    environment:
      APP_NAME: tracking-service
      API_HOST: 0.0.0.0
      API_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: drone-events
      KAFKA_GROUP_ID: tracking-service
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: tracking
      MONGO_COLLECTION_NAME: tracking_states
      DELIVERY_SERVICE_BASE_URL: http://host.docker.internal:8080
    ports:
      - "8083:8080"


  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  dronefleet-service:
    build: ./dronefleet-service
    container_name: dronefleet-service
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./logs:/app/logs


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - delivery-service
      - payment-service
      - dronefleet-service
      - notification-service
