server:
  port: ${SERVER_PORT:8083}

services:
  payment:
    base-url: ${PAYMENT_BASE_URL:http://localhost:8083/payments}

payment:
  callback:
    url: ${PAYMENT_CALLBACK_URL:http://localhost:8083/payments}

spring:
  data:
    mongodb:
      uri: ${PAYMENT_MONGODB_URI:mongodb://localhost:27017/payment}
  kafka:
    consumer:
      group-id: payment-service
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
