server:
  port: ${SERVER_PORT:8081}

services:
  delivery:
    base-url: ${DELIVERY_BASE_URL:http://localhost:8080/deliveries}

spring:
  data:
    mongodb:
      uri: ${USER_MONGODB_URI:mongodb://localhost:27017/user}
  kafka:
    consumer:
      group-id: user-service
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
